### ISSUE TITLE
[Documentation]: stale references to os_pid

### ISSUE THREAD

**Issue by simark** [ROCm-Developer-Tools/ROCdbgapi#13]
### Description of errors

There are some stale references to the `get_os_pid` callback or related parameters that don't exist anymore:

https://github.com/ROCm/ROCdbgapi/blob/d2322002b813dd7c5278c3077200e3062d3caacf/include/amd-dbgapi.h.in#L7399-L7410
https://github.com/ROCm/ROCdbgapi/blob/d2322002b813dd7c5278c3077200e3062d3caacf/include/amd-dbgapi.h.in#L1864

**Comment by lancesix** [comment]
Fixed in 59da36d771b74bbcb0e901c125952a25567d8253.
